// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/16/2025, 7:04:36 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/EPU-Web/frontend2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend2/plugins/**/*.{js,ts,mjs}","D:/EPU-Web/frontend2/composables/**/*.{js,ts,mjs}","D:/EPU-Web/frontend2/utils/**/*.{js,ts,mjs}","D:/EPU-Web/frontend2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend2/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;