// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 16:01:26 16/10/2025
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/EPU-Web/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend/plugins/**/*.{js,ts,mjs}","D:/EPU-Web/frontend/composables/**/*.{js,ts,mjs}","D:/EPU-Web/frontend/utils/**/*.{js,ts,mjs}","D:/EPU-Web/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/EPU-Web/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;